### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Jinjiang** [weexteam/weex-vdom-tester#1]
* [ ] main features
  * [x] mock DOM APIs
    * [x] createBody
    * [x] addElement
    * [x] removeElement
    * [x] moveElement
    * [x] addEvent
    * [x] removeEvent
    * [x] updateAttr
    * [x] updateStyle
  * [ ] mock module APIs
    * [x] timer
    * [ ] stream
    * [ ] storage
    * [x] modal
  * [ ] known native bugs
  * [x] mock WXEnvironment
  * [x] get vdom object
  * [ ] read and validate input & output
* [x] API
  * [x] instance management
    * [x] create
    * [x] refresh
    * [x] destroy
  * [x] register
    * [x] modules
    * [x] components
  * [x] fire event
  * [x] mock module API
  * [x] get instance root
  * [x] watch instance dom changes

**Comment by Jinjiang** [comment]
I use [Projects](https://github.com/weexteam/weex-vdom-tester/projects/1?fullscreen=true) instead
